### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by MarvinSchramm** [creativetimofficial/vue-now-ui-kit#4]
We want to use this kit for an open source project and it seems that the License that is mentioned in the README is not there anymore. For us it is unclear now if the current state of the code is still licensed under MIT.

**Comment by alexandru-paduraru** [comment]
@MarvinSchramm sorry for the issue, somehow we missed that file. The product is still under MIT License, so you can use it without issues. Just added back the file: https://github.com/creativetimofficial/vue-now-ui-kit/blob/master/LICENSE.md

**Comment by MarvinSchramm** [comment]
Thank you very much @alexandru-paduraru !
